title: Lewis O'Driscoll
author: Lewis O'Driscoll
description: >-
  Lewis O'Driscoll's blog about all things software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lewis-od.co.uk"

navbar-links:
  Blog: "/"
  Tags: "tags"
  About: "about"

social-network-links:
  github: lewis-od
  linkedin: lewis-odriscoll

theme: beautiful-jekyll-theme
plugins:
  - jekyll-paginate
  - jekyll-sitemap
